#!/bin/bash

# declare -a arr=("element1" "element2" "element3")

# if [[ " ${arr[@]} " =~ " ${element1} " ]]; then
#     # whatever you want to do when arr contains value
#     echo yes
# fi

git fetch
echo --------------------
git checkout origin/3.5FRD
echo --------------------
git reset --hard orogin/3.5FRD
echo --------------------
git pull
echo --------------------
git status
echo --------------------
