#!/bin/zsh
source "${0:A:h}/../functions/hp.sh"

$HUAWEI_IP = "192.168.0.18"

case "$1" in 
	"ssh")
		ssh artur@192.168.0.18 
	;;

	"cred")
		ec "root  ---  aUT?#1pPv*N34U " ;;

	"devgo")
		br "https://дев.жкх15.рф/login" ;;

	
esac

