#!/bin/zsh
source "${0:A:h}/../functions/hp.sh"

case "$1" in 
	"ssh")
		ssh arturgudiev@158.160.36.7 ;;

	"ip")
		ec "158.160.36.7" ;;

	"cred")
		ec "root  ---  aUT?#1pPv*N34U " ;;

	"devgo")
		br "https://дев.жкх15.рф/login" ;;

	"cursor")
		cursor --remote ssh-remote+arturgudiev@158.160.36.7  /home/arturgudiev ;;

	"dash"|"dashboard")
		cursor --remote ssh-remote+arturgudiev@158.160.36.7  /home/arturgudiev/Projects/memory-guard/ ;;

	"bash"|"scripts")
		cursor --remote ssh-remote+arturgudiev@158.160.36.7  /home/arturgudiev/Programming/Bash/ ;;
	

	"rc"|"remote_command")
		ssh -t arturgudiev@158.160.36.7 "bash -l -c '$2'"
		;;

	"ru"|"remote_update")
		yavm rc "da ubf"
		;;

	"cptemp"|"copy_to_temp")
		scp $2 arturgudiev@158.160.36.7:/tmp
		;;
	
	
esac

