#!/bin/zsh
case "$1" in 
	"dir")
		cd /Users/arturgudiev/Programming/Job/chp_online_mobile ;;
	
	"dirb")
		cd /Users/arturgudiev/Programming/Job/chp_online_mobile ;;

	"sh")
		cd ~/Programming/Bash ;;

	"figma")
        open -a "Safari" "https://www.figma.com/design/Z5XpqNHhROerYLdU2UIVjb/%D0%9C%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D0%B5%D1%80%D1%81%D1%82%D0%B2%D0%BE-%D0%96%D0%9A%D0%A5-%D0%A0%D0%A1%D0%9E-%D0%90%D0%BB%D0%B0%D0%BD%D0%B8%D1%8F?node-id=451-2&t=YRkkMrYT8iBkvsE3-1" ;;

	"pro")
        code "/Users/arturgudiev/Programming/Job/chp_online_mobile" ;;
	
	"hub")
        br code "/Users/arturgudiev/Programming/Job/chp_online_mobile" ;;


esac

# exec zsh
