#!/bin/zsh
case "$1" in 
	"fclean"|"fc")
		flutter pub run build_runner clean ;;
		# flutter run build_runner clean ;;
		# dart run build_runner clean ;;
	"fbuild"|"fb")
		# dart run build_runner build --delete-conflicting-outputs ;;
		flutter pub run build_runner build --delete-conflicting-outputs ;;

esac

# exec zsh
