#!/bin/zsh
case "$1" in 
	"fclean"|"fc")
		flutter pub run build_runner clean ;;

	"fbuild"|"fb")
		flutter pub run build_runner build --delete-conflicting-outputs ;;

	"color"|"col")
		color=${2:-$(pbpaste)}
		
		if [[ $color == \#* ]]; then
			pureColor="${color:1}"
			ec "Color(0xFF$pureColor)"
		fi
		;;

	"colorc"|"colc")
		color=${2:-$(pbpaste)}
		
		if [[ $color == \#* ]]; then
			pureColor="${color:1}"
			ec "const Color(0xFF$pureColor)"
		fi
		;;

esac
